- name: settingup frontend nginx
  hosts: frontend
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enabel and starting nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started
  
  - name: Delete default html directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html

  - name: creating html directory
    ansible.builtin.file:
      state: directory
      path: /usr/share/nginx/html

  - name: downloading frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unziping the frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense configuration
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restarting the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted