- name: configuring mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
  
  - name: enable the server
    ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started

  # - name: 
  